name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout репозитория
      - name: Checkout code
        uses: actions/checkout@v4

      # 2️⃣ Установка Bun
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      # 3️⃣ Установка зависимостей
      - name: Install dependencies
        run: npm install --frozen-lockfile

      # 4  Генерация prisma client
      - name: Generate prisma client
        run: npx prisma generate

      # 4️⃣ Lint
      - name: Lint
        run: npm run lint

      # 5️⃣ Format (prettier)
      - name: Format check
        run: npm run format

      # 6️⃣ E2E tests
      - name: E2E tests
        env:
          NODE_ENV: test
        run: npm run test:e2e

      # 7️⃣ Build
      - name: Build
        run: npm run build

      # 8️⃣ Knip (unused exports / deps)
      - name: Knip
        run: npm run knip || true
